const assert = require('node:assert/strict');
require('./src/razor_console/static/toml-editor.js');
const {highlight,commentSelection}=globalThis.RazorToml;
const {commentMode}=globalThis.RazorToml;
assert.equal(commentMode('# a\n  # b\n', 0, 10), 'uncomment');
assert.equal(commentMode('# a\nb=2', 0, 7), 'comment');
assert.equal(commentMode('\n  \n', 0, 4), 'comment');
assert.equal(commentMode('# a\nb=2', 0, 4), 'uncomment');
const source='pattern = [\n  [0.1, 0, 8],\n  # preset\n]\n';
let changed=commentSelection(source,source.indexOf('  [0.1'),source.indexOf('  # preset'),'comment');
assert.ok(changed.text.includes('  # [0.1, 0, 8],'));
changed=commentSelection(changed.text,changed.start,changed.end,'uncomment');
assert.equal(changed.text,source);
assert.equal(commentSelection('x=1\ny=2\n',0,4,'comment').text,'# x=1\ny=2\n');
assert.equal(commentSelection('  # x=1',0,8,'toggle').text,'  x=1');
assert.equal(commentSelection('a\nb',2,2,'comment').text,'a\n# b');
const tokens=highlight('[component.X]\nflag=true\nn=0.3\nrule="""# inside string\n<script>"""\n# comment');
assert.ok(tokens.includes('toml-section'));
assert.ok(tokens.includes('toml-boolean'));
assert.ok(tokens.includes('toml-number'));
assert.ok(tokens.includes('toml-string'));
assert.ok(tokens.includes('toml-comment'));
assert.ok(!tokens.includes('<script>'));
assert.ok(tokens.includes('&lt;script&gt;'));
console.log('TOML highlighting and selection/comment edge cases passed');
